# Generated by Django 3.1.7 on 2021-06-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listings',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
