# Generated by Django 3.1.7 on 2021-06-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210614_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('all', 'all'), ('video games', 'video games'), ('cars', 'cars'), ('home equipment', 'home equipment'), ('clothes', 'clothes'), ('electronic devices', 'electronic devices'), ('others', 'others')], max_length=128),
        ),
    ]
